name : Business Owner CI
on:
  push:
    branches : 
      - "main"
    
jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - run : npm install
      - run : npm run build
      - run : sudo rm -r /var/www/business/build
      - run : sudo mv /home/mbe/actions-runner-two/_work/business-owner/business-owner/build /var/www/business/
      - run : sudo cp /var/www/.htaccess /var/www/business/build
